name = "wizdevtechlanding26"
compatibility_date = "2024-12-01"

main = ".vercel/output/static/_worker.js"

[build]
command = "bun run build:worker"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"

[env.production]
pages_build_output_dir = ".vercel/output/static"

